export type CuratedBook = {
  title: string;
  author: string;
};

export type CuratedList = {
  id: string;
  title: string;
  books: CuratedBook[];
};

export const CURATED_LISTS: CuratedList[] = [
  {
    id: "classics",
    title: "Classics",
    books: [
      { title: "Pride and Prejudice", author: "Jane Austen" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "Moby-Dick", author: "Herman Melville" },
      { title: "Great Expectations", author: "Charles Dickens" },
      { title: "The Odyssey", author: "Homer" },
      { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "Middlemarch", author: "George Eliot" },
    ],
  },
  {
    id: "strange-fiction",
    title: "Strange fiction",
    books: [
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "Dracula", author: "Bram Stoker" },
      { title: "The Time Machine", author: "H. G. Wells" },
      { title: "The War of the Worlds", author: "H. G. Wells" },
      { title: "The Yellow Wallpaper", author: "Charlotte Perkins Gilman" },
      { title: "The Horla", author: "Guy de Maupassant" },
      { title: "The Great God Pan", author: "Arthur Machen" },
      { title: "The King in Yellow", author: "Robert W. Chambers" },
    ],
  },
  {
    id: "nonfiction",
    title: "Nonfiction",
    books: [
      { title: "Walden", author: "Henry David Thoreau" },
      { title: "The Souls of Black Folk", author: "W. E. B. Du Bois" },
      { title: "Narrative of the Life of Frederick Douglass", author: "Frederick Douglass" },
      { title: "The Autobiography of Benjamin Franklin", author: "Benjamin Franklin" },
      { title: "A Room of One's Own", author: "Virginia Woolf" },
      { title: "On Liberty", author: "John Stuart Mill" },
      { title: "Up from Slavery", author: "Booker T. Washington" },
      { title: "Incidents in the Life of a Slave Girl", author: "Harriet Jacobs" },
    ],
  },
  {
    id: "science",
    title: "Science",
    books: [
      { title: "On the Origin of Species", author: "Charles Darwin" },
      { title: "Relativity: The Special and General Theory", author: "Albert Einstein" },
      { title: "Micrographia", author: "Robert Hooke" },
      { title: "The Chemical History of a Candle", author: "Michael Faraday" },
      { title: "The Voyage of the Beagle", author: "Charles Darwin" },
      { title: "The Story of the Heavens", author: "Robert Stawell Ball" },
      { title: "The Grammar of Science", author: "Karl Pearson" },
      { title: "The Analysis of Sensations", author: "Ernst Mach" },
    ],
  },
  {
    id: "philosophy",
    title: "Philosophy",
    books: [
      { title: "The Republic", author: "Plato" },
      { title: "Meditations", author: "Marcus Aurelius" },
      { title: "Beyond Good and Evil", author: "Friedrich Nietzsche" },
      { title: "Ethics", author: "Baruch Spinoza" },
      { title: "Tao Te Ching", author: "Laozi" },
      { title: "Second Treatise of Government", author: "John Locke" },
      { title: "The Enchiridion", author: "Epictetus" },
      { title: "The Problems of Philosophy", author: "Bertrand Russell" },
    ],
  },
  {
    id: "history",
    title: "History",
    books: [
      { title: "The History of the Decline and Fall of the Roman Empire", author: "Edward Gibbon" },
      { title: "History of the Peloponnesian War", author: "Thucydides" },
      { title: "The Histories", author: "Herodotus" },
      { title: "The French Revolution", author: "Thomas Carlyle" },
      { title: "History of the Conquest of Mexico", author: "William H. Prescott" },
      { title: "The History of England", author: "Thomas Babington Macaulay" },
      { title: "The Conquest of Gaul", author: "Julius Caesar" },
      { title: "The Life of Charlemagne", author: "Einhard" },
    ],
  },
  {
    id: "politics",
    title: "Politics",
    books: [
      { title: "Common Sense", author: "Thomas Paine" },
      { title: "The Federalist Papers", author: "Alexander Hamilton, James Madison and John Jay" },
      { title: "Rights of Man", author: "Thomas Paine" },
      { title: "The Communist Manifesto", author: "Karl Marx and Friedrich Engels" },
      { title: "A Vindication of the Rights of Woman", author: "Mary Wollstonecraft" },
      { title: "Civil Disobedience", author: "Henry David Thoreau" },
      { title: "The Prince", author: "Niccolò Machiavelli" },
      { title: "Politics", author: "Aristotle" },
    ],
  },
  {
    id: "children",
    title: "Children",
    books: [
      { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll" },
      { title: "The Wonderful Wizard of Oz", author: "L. Frank Baum" },
      { title: "Peter Pan", author: "J. M. Barrie" },
      { title: "The Wind in the Willows", author: "Kenneth Grahame" },
      { title: "The Secret Garden", author: "Frances Hodgson Burnett" },
      { title: "Anne of Green Gables", author: "L. M. Montgomery" },
      { title: "Treasure Island", author: "Robert Louis Stevenson" },
      { title: "Little Women", author: "Louisa May Alcott" },
    ],
  },
  {
    id: "poetry",
    title: "Poetry",
    books: [
      { title: "Leaves of Grass", author: "Walt Whitman" },
      { title: "Songs of Innocence and of Experience", author: "William Blake" },
      { title: "Poems by Emily Dickinson", author: "Emily Dickinson" },
      { title: "The Canterbury Tales", author: "Geoffrey Chaucer" },
      { title: "The Divine Comedy", author: "Dante Alighieri" },
      { title: "Goblin Market and Other Poems", author: "Christina Rossetti" },
      { title: "The Raven and Other Poems", author: "Edgar Allan Poe" },
      { title: "Shakespeare's Sonnets", author: "William Shakespeare" },
    ],
  },
  {
    id: "mystery",
    title: "Mystery",
    books: [
      { title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle" },
      { title: "The Moonstone", author: "Wilkie Collins" },
      { title: "The Woman in White", author: "Wilkie Collins" },
      { title: "The Murders in the Rue Morgue", author: "Edgar Allan Poe" },
      { title: "The Mystery of the Yellow Room", author: "Gaston Leroux" },
      { title: "The Thirty-Nine Steps", author: "John Buchan" },
      { title: "The Lodger", author: "Marie Belloc Lowndes" },
      { title: "The Mystery of Cloomber", author: "Arthur Conan Doyle" },
    ],
  },
  {
    id: "short-reads",
    title: "Short reads",
    books: [
      { title: "The Metamorphosis", author: "Franz Kafka" },
      { title: "Strange Case of Dr Jekyll and Mr Hyde", author: "Robert Louis Stevenson" },
      { title: "The Turn of the Screw", author: "Henry James" },
      { title: "The Call of the Wild", author: "Jack London" },
      { title: "The Death of Ivan Ilyich", author: "Leo Tolstoy" },
      { title: "The Importance of Being Earnest", author: "Oscar Wilde" },
      { title: "Bartleby, the Scrivener", author: "Herman Melville" },
      { title: "The Story of an Hour", author: "Kate Chopin" },
    ],
  },
  {
    id: "adventure",
    title: "Adventure",
    books: [
      { title: "Kidnapped", author: "Robert Louis Stevenson" },
      { title: "King Solomon's Mines", author: "H. Rider Haggard" },
      { title: "Around the World in Eighty Days", author: "Jules Verne" },
      { title: "The Prisoner of Zenda", author: "Anthony Hope" },
      { title: "The Lost World", author: "Arthur Conan Doyle" },
      { title: "Captain Blood", author: "Rafael Sabatini" },
      { title: "The Sea-Wolf", author: "Jack London" },
      { title: "The Coral Island", author: "R. M. Ballantyne" },
    ],
  },
  {
    id: "gothic",
    title: "Gothic",
    books: [
      { title: "The Castle of Otranto", author: "Horace Walpole" },
      { title: "The Mysteries of Udolpho", author: "Ann Radcliffe" },
      { title: "Northanger Abbey", author: "Jane Austen" },
      { title: "Carmilla", author: "Sheridan Le Fanu" },
      { title: "The House of the Seven Gables", author: "Nathaniel Hawthorne" },
      { title: "The Monk", author: "Matthew Lewis" },
      { title: "Melmoth the Wanderer", author: "Charles Maturin" },
      { title: "Vathek", author: "William Beckford" },
    ],
  },
  {
    id: "science-fiction",
    title: "Science fiction",
    books: [
      { title: "From the Earth to the Moon", author: "Jules Verne" },
      { title: "Twenty Thousand Leagues Under the Seas", author: "Jules Verne" },
      { title: "The First Men in the Moon", author: "H. G. Wells" },
      { title: "The Invisible Man", author: "H. G. Wells" },
      { title: "Flatland", author: "Edwin A. Abbott" },
      { title: "A Princess of Mars", author: "Edgar Rice Burroughs" },
      { title: "Erewhon", author: "Samuel Butler" },
      { title: "The Last Man", author: "Mary Shelley" },
    ],
  },
  {
    id: "economics",
    title: "Economics",
    books: [
      { title: "The Wealth of Nations", author: "Adam Smith" },
      { title: "Principles of Political Economy", author: "John Stuart Mill" },
      { title: "Capital, Volume I", author: "Karl Marx" },
      { title: "The Economic Consequences of the Peace", author: "John Maynard Keynes" },
      { title: "The Theory of the Leisure Class", author: "Thorstein Veblen" },
      { title: "Progress and Poverty", author: "Henry George" },
      { title: "Mutual Aid", author: "Peter Kropotkin" },
      { title: "What Is Property?", author: "Pierre-Joseph Proudhon" },
    ],
  },
  {
    id: "essays",
    title: "Essays",
    books: [
      { title: "Essays", author: "Michel de Montaigne" },
      { title: "Essays", author: "Ralph Waldo Emerson" },
      { title: "Essays of Elia", author: "Charles Lamb" },
      { title: "The Common Reader", author: "Virginia Woolf" },
      { title: "The Art of Literature", author: "Arthur Schopenhauer" },
      { title: "Sesame and Lilies", author: "John Ruskin" },
      { title: "Walking", author: "Henry David Thoreau" },
      { title: "The Decay of Lying", author: "Oscar Wilde" },
    ],
  },
  {
    id: "travel",
    title: "Travel",
    books: [
      { title: "Travels with a Donkey in the Cévennes", author: "Robert Louis Stevenson" },
      { title: "The Innocents Abroad", author: "Mark Twain" },
      { title: "Italian Hours", author: "Henry James" },
      { title: "Travels in the Interior Districts of Africa", author: "Mungo Park" },
      { title: "A Journey to the Western Islands of Scotland", author: "Samuel Johnson" },
      { title: "The Oregon Trail", author: "Francis Parkman" },
      { title: "The Malay Archipelago", author: "Alfred Russel Wallace" },
      { title: "Seven Pillars of Wisdom", author: "T. E. Lawrence" },
    ],
  },
  {
    id: "memoir",
    title: "Memoir",
    books: [
      { title: "My Bondage and My Freedom", author: "Frederick Douglass" },
      { title: "Confessions", author: "Jean-Jacques Rousseau" },
      { title: "Confessions of an English Opium-Eater", author: "Thomas De Quincey" },
      { title: "The Story of My Experiments with Truth", author: "Mahatma Gandhi" },
      { title: "Personal Memoirs of U. S. Grant", author: "Ulysses S. Grant" },
      { title: "The Interesting Narrative of the Life of Olaudah Equiano", author: "Olaudah Equiano" },
      { title: "The Journal of Marie Bashkirtseff", author: "Marie Bashkirtseff" },
      { title: "The Memoirs of Casanova", author: "Giacomo Casanova" },
    ],
  },
  {
    id: "drama",
    title: "Drama",
    books: [
      { title: "Hamlet", author: "William Shakespeare" },
      { title: "Macbeth", author: "William Shakespeare" },
      { title: "A Doll's House", author: "Henrik Ibsen" },
      { title: "Pygmalion", author: "George Bernard Shaw" },
      { title: "The Cherry Orchard", author: "Anton Chekhov" },
      { title: "Tartuffe", author: "Molière" },
      { title: "The Duchess of Malfi", author: "John Webster" },
      { title: "The Playboy of the Western World", author: "J. M. Synge" },
    ],
  },
  {
    id: "social-thought",
    title: "Social thought",
    books: [
      { title: "The Subjection of Women", author: "John Stuart Mill" },
      { title: "Women and Economics", author: "Charlotte Perkins Gilman" },
      { title: "The Condition of the Working Class in England", author: "Friedrich Engels" },
      { title: "The Ragged-Trousered Philanthropists", author: "Robert Tressell" },
      { title: "Looking Backward", author: "Edward Bellamy" },
      { title: "News from Nowhere", author: "William Morris" },
      { title: "Herland", author: "Charlotte Perkins Gilman" },
      { title: "The Conquest of Bread", author: "Peter Kropotkin" },
    ],
  },
  {
    id: "women-at-the-edge",
    title: "Women at the edge",
    books: [
      { title: "The Awakening", author: "Kate Chopin" },
      { title: "The House of Mirth", author: "Edith Wharton" },
      { title: "The Story of an African Farm", author: "Olive Schreiner" },
      { title: "The Tenant of Wildfell Hall", author: "Anne Brontë" },
      { title: "Villette", author: "Charlotte Brontë" },
      { title: "North and South", author: "Elizabeth Gaskell" },
      { title: "The Mill on the Floss", author: "George Eliot" },
      { title: "The Enchanted April", author: "Elizabeth von Arnim" },
    ],
  },
];

export const CURATED_LIST_DESCRIPTIONS: Record<string, string> = {
  classics: "Austen · Brontë · Melville · Dickens",
  "strange-fiction": "Shelley · Stoker · Wells · Machen",
  nonfiction: "Thoreau · Du Bois · Douglass · Woolf",
  science: "Darwin · Einstein · Hooke · Faraday",
  philosophy: "Plato · Aurelius · Nietzsche · Spinoza",
  history: "Gibbon · Thucydides · Herodotus · Caesar",
  politics: "Paine · Wollstonecraft · Marx · Mill",
  children: "Carroll · Baum · Barrie · Grahame",
  poetry: "Whitman · Blake · Dickinson · Rossetti",
  mystery: "Doyle · Collins · Poe · Leroux",
  "short-reads": "Kafka · Stevenson · James · Tolstoy",
  adventure: "Stevenson · Haggard · Verne · London",
  gothic: "Walpole · Radcliffe · Le Fanu · Maturin",
  "science-fiction": "Verne · Wells · Abbott · Shelley",
  economics: "Smith · Mill · Marx · Keynes",
  essays: "Montaigne · Emerson · Lamb · Woolf",
  travel: "Stevenson · Twain · James · Wallace",
  memoir: "Douglass · Rousseau · Gandhi · Grant",
  drama: "Shakespeare · Ibsen · Shaw · Chekhov",
  "social-thought": "Mill · Gilman · Engels · Morris",
  "women-at-the-edge": "Chopin · Wharton · Schreiner · Gaskell",
};
